services:
  db:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    restart: unless-stopped

  redis:
    container_name: redis
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    network_mode: host
    env_file: 
      - .env
    volumes:
      - ./data/redis:/data
    command: ["--requirepass", "${REDIS_PASSWORD}"]
    restart: unless-stopped