import Navbar from "@/components/NavBar";
import Loaders from "@/loaders/Loaders";
import Providers from "@/providers/Providers";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`dark ${inter.className}`}>
        {" "}
        <Providers>
          <Loaders>
            <Navbar />
            {children}
          </Loaders>
        </Providers>
      </body>
    </html>
  );
}
